apiVersion: v1
kind: ConfigMap
metadata:
  name: logistics-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "agri-rabbitmq"
  RabbitMq__Port: "5672"
  SomeFeature__Enabled: "true"
