name: Build & Push Logistics Image

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/docker-build-push.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Code checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build & Push image
      - name: Build and push logistics image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ogabek0331/logistics:latest
            ogabek0331/logistics:${{ github.sha }}
